debug: true

# Spring configuration
spring:
#   datasource:
#    url: jdbc:mysql://localhost:3306/online_ride_hailing_db?useUnicode=true&characterEncoding=UTF-8
#    type: com.alibaba.druid.pool.DruidDataSource
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true
#      stat-view-servlet.allow: true
  # Jackson
  jackson:
    serialization:
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #default-property-inclusion: non_null
  # H2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  # static resource path
  resources:
    static-locations: classpath:static/,file:static/

#Mybatis
mybatis:
  type-aliases-package: com.gd.orh.entity
  mapper-locations: classpath:com/gd/orh/mapper/*.xml

#Mapper
mapper:
  mappers:
    - com.gd.orh.utils.MyMapper
  not-empty: false
  identity: MYSQL

#Pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      login: api/auth/login
      register: api/auth/register
      refresh: api/auth/refresh
      verify: api/auth/verify

# Logging configuration
logging:
  level:
    tk.mybatis: TRACE
    com.gd.orh.mapper: DEBUG
    org.springframework:
      security: DEBUG
