DROP TABLE IF EXISTS AUTHORITY;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USER_AUTHORITY;
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS DRIVER;
DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS TRIP_ORDER;
DROP TABLE IF EXISTS DRIVING_LICENSE;
DROP TABLE IF EXISTS VEHICLE_LICENSE;
DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS FARE_RULE;
DROP TABLE IF EXISTS FARE;
DROP TABLE IF EXISTS SERVICE_RATING;
DROP TABLE IF EXISTS DRIVER_BALANCE;

CREATE TABLE AUTHORITY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  NICKNAME VARCHAR(255),
  GENDER VARCHAR(255),
  AGE INT,
  ENABLED INT,
  LAST_PASSWORD_RESET_DATE DATETIME,
  PRIMARY KEY (ID)
);

CREATE TABLE USER_AUTHORITY (
  USER_ID BIGINT,
  AUTHORITY_ID BIGINT,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY (ID)
);

CREATE TABLE PASSENGER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE DRIVER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DRIVER_STATUS VARCHAR(255),
  USER_ID BIGINT,
  FOREIGN KEY (USER_ID) REFERENCES USER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE FARE_RULE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  INITIAL_PRICE DECIMAL(10,2),
  INITIAL_MILEAGE DECIMAL(10,2),
  UNIT_PRICE_PER_KILOMETER DECIMAL(10,2),
  UNIT_PRICE_PER_MINUTE DECIMAL(10,2),
  SETUP_TIME DATETIME,
  PRIMARY KEY (ID)
);

CREATE TABLE FARE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  LENGTH_OF_MILEAGE DECIMAL(10,2),
  LENGTH_OF_TIME DECIMAL(10,2),
  FARE_RULE_ID BIGINT,
  FOREIGN KEY (FARE_RULE_ID) REFERENCES FARE_RULE (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE TRIP (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DEPARTURE VARCHAR(255),
  DEPARTURE_LOCATION VARCHAR(255),
  DESTINATION VARCHAR(255),
  DESTINATION_LOCATION VARCHAR(255),
  CREATED_TIME DATETIME,
  DEPARTURE_TIME DATETIME,
  TRIP_TYPE VARCHAR(255),
  TRIP_STATUS VARCHAR(255),
  PASSENGER_ID BIGINT,
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE TRIP_ORDER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OUT_TRADE_NO VARCHAR(255) NOT NULL UNIQUE,
  ACCEPTED_TIME DATETIME,
  COMPLETED_TIME DATETIME,
  ORDER_STATUS VARCHAR(255),
  TRIP_ID BIGINT,
  DRIVER_ID BIGINT,
  FARE_ID BIGINT,
  FOREIGN KEY (TRIP_ID) REFERENCES TRIP (ID),
  FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID),
  FOREIGN KEY (FARE_ID) REFERENCES FARE (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE DRIVING_LICENSE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DRIVER_NAME VARCHAR(255),
  IDENTIFICATION VARCHAR(255),
  ISSUE_DATE DATETIME,
  DRIVER_ID BIGINT,
  FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE VEHICLE_LICENSE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OWNER VARCHAR(255),
  REGISTER_DATE DATETIME,
  DRIVER_ID BIGINT,
  FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE CAR (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  PLATE_NO VARCHAR(255),
  BRAND VARCHAR(255),
  SERIES VARCHAR(255),
  COLOR VARCHAR(255),
  VEHICLE_LICENSE_ID BIGINT,
  FOREIGN KEY (VEHICLE_LICENSE_ID) REFERENCES VEHICLE_LICENSE (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE SERVICE_RATING (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  IS_PASSENGER_RATIED BIT,
  PASSENGER_RATING_SCORE DECIMAL(10,2),
  PASSENGER_RATING_CONTENT VARCHAR(255),
  IS_DRIVER_RATIED BIT,
  DRIVER_RATING_SCORE DECIMAL(10,2),
  DRIVER_RATING_CONTENT VARCHAR(255),
  TRIP_ORDER_ID BIGINT,
  PASSENGER_ID BIGINT,
  DRIVER_ID BIGINT,
  FOREIGN KEY (TRIP_ORDER_ID) REFERENCES TRIP_ORDER (ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (ID),
  FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID),
  PRIMARY KEY (ID)
);

CREATE TABLE DRIVER_BALANCE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ALIPAY_ACCOUNT VARCHAR(255),
  BALANCE DECIMAL(10,2),
  DRIVER_ID BIGINT,
  FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID),
  PRIMARY KEY (ID)
);
